name: Docs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_docs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache docs build
        id: cache-docs
        uses: actions/cache@v4
        with:
          key: docs-build-${{ github.run_id }}-${{ github.run_attempt }}
          path: docs/build

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test,doc]

      - name: Build docs
        run: |
          cd docs && make html

      # Create an artifact of the html output.
      - uses: actions/upload-artifact@v4
        with:
          name: DocumentationHTML
          path: docs/build/html/

  deploy_gh_pages:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build_docs
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Restore cached docs build
        id: cache-docs
        uses: actions/cache/restore@v4
        with:
          key: docs-build-${{ github.run_id }}-${{ github.run_attempt }}
          path: docs/build

      - name: Check cache hit
        if: steps.cache-docs.outputs.cache-hit != 'true'
        run: exit 1

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          destination_dir: docs/
          publish_branch: gh-pages
          publish_dir: ./docs/build/html
          cname: growingnet.github.io/gromo/
