name: Docs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    environment: github-pages
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test,doc]

      - name: Build docs
        run: |
          cd docs && make html

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: DocumentationHTML
          path: docs/build/html/

  deploy_gh_pages:
    needs: build_docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: DocumentationHTML
          path: docs/build/html/

      - name: Add CNAME
        run: echo 'growingnet.github.io/gromo/' > docs/build/html/CNAME

      - name: Check GITHUB_TOKEN Info
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "GH_PAT: ${{ secrets.GH_PAT }}"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/build/html
          external_repository: growingnet/gromo
