name: Ruff Linting
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff-check:
    name: Ruff Linting
    runs-on: ubuntu-latest
    continue-on-error: true  # Makes this check non-blocking
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run ruff linting
        run: |
          ruff check --output-format=github .

      - name: Run ruff formatting check
        run: |
          ruff format --check .
