name: Tests
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: dev ${{ matrix.os }}, py-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # windows-latest, macOS-latest -> problem with MAGMA/CUDA 12.1
        os: [ ubuntu-latest ]
        python-version: [ "3.11", "3.12" ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: pre-commit/action@v3.0.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Run tests
        run: |
          coverage run -m unittest
          coverage xml
          coverage report -m

      # - uses: codecov/codecov-action@v5
      #   with:
      #     fail_ci_if_error: true
      #     files: ./coverage.xml
      #     flags: unittests
      #     name: codecov-ci-gromo
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     verbose: true
      #     slug: growingnet/gromo

      - name: Codecov report
        run: |
          pip install codecov-cli
          codecovcli -v create-commit --slug growingnet/gromo --git-service github --commit-sha ${{ github.sha }}  --token ${{ secrets.CODECOV_TOKEN }}
          codecovcli -v create-report --code codecov-ci-gromo --slug growingnet/gromo --git-service github --token ${{ secrets.CODECOV_TOKEN }}
          codecovcli -v do-upload --report-code codecov-ci-gromo -f coverage.xml --slug growingnet/gromo --git-service github --token ${{ secrets.CODECOV_TOKEN }}
          codecovcli -v create-report-results --code codecov-ci-gromo --slug growingnet/gromo --git-service github --token ${{ secrets.CODECOV_TOKEN }}
